//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dekerf_steve_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class model1 : DbContext
    {
        public model1()
            : base("name=model1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Proj_evenementen> Proj_evenementen { get; set; }
        public virtual DbSet<Proj_gemeenten> Proj_gemeenten { get; set; }
        public virtual DbSet<Proj_pers> Proj_pers { get; set; }
    }
}
