//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dekerf_steve_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proj_gemeenten
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proj_gemeenten()
        {
            this.Proj_evenementen = new HashSet<Proj_evenementen>();
            this.Proj_pers = new HashSet<Proj_pers>();
        }
    
        public int id { get; set; }
        public string naam { get; set; }
        public Nullable<int> postcode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proj_evenementen> Proj_evenementen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proj_pers> Proj_pers { get; set; }
    }
}
